### ISSUE TITLE
Time related error on grib2 datasets

### ISSUE THREAD

**Issue by NicholasMarkou** [xpublish-community/xpublish-wms#48]
When requesting tiles from xpublish-wms using our grib2 datasets, we get the resulting error:
`ValueError: Dimensions {'time'} do not exist. Expected one or more of ('latitude', 'longitude')`

Ran on Ubuntu 23.10, using xpublish-wms commit 36e44b4 , on Python 3.11.6

Server code:
```
import xarray as xr
import xpublish


ds = xr.open_dataset('./gfswave.t12z.global.0p16.f001.grib2', chunks={})
ds.rest.serve()
```

Link to tile request that causes this error: http://localhost:9000/wms/?FORMAT=image%2Fpng&TRANSPARENT=TRUE&STYLES=default-scalar%2Fdefault&LAYERS=ws&COLORSCALERANGE=-1.082%2C24.48&NUMCOLORBANDS=250&ABOVEMAXCOLOR=0x000000&BELOWMINCOLOR=0x000000&BGCOLOR=transparent&LOGSCALE=false&SERVICE=WMS&VERSION=1.3.0&REQUEST=GetMap&SRS=EPSG%3A4326&BBOX=135.0,5.615985819155334,140.625,11.178401873711781&WIDTH=256&HEIGHT=256 

Bug occurred on the following GRIB2 datasets: [GRIB2_datasets.zip](https://github.com/xpublish-community/xpublish-wms/files/13640959/GRIB2_datasets.zip)

@mpiannucci

**Comment by mpiannucci** [comment]
@NicholasMarkou can you give the main branch a test now? Quick test showed the grib files you attached to work fine and would love to know if it works for you

**Comment by NicholasMarkou** [comment]
@mpiannucci The new main branch has fixed the issue

**Comment by pjsalisbury** [comment]
This fixes the issue for GRIB2 datasets, but in turn causes an issue with our (working) NetCDF dataset.

`ValueError: DataArray ssh is backed by a Dask array, 
but coordinate x is not backed by a Dask array with identical 
dimension order and chunks`

This is the same error we were getting with our interim fix that got GRIB2 files working in the past, so we have seen this before.

Here is a direct link to an example dataset with the issue (it may apply to other NetCDF datasets but we are having a separate issue with those):
https://noaa-nws-rtofs-pds.s3.amazonaws.com/rtofs.20230925/rtofs_glo_2ds_f001_diag.nc

**Comment by mpiannucci** [comment]
Ok test with latest main when you get a chance please!
