### ISSUE TITLE
TypeError with certain NetCDF datasets

### ISSUE THREAD

**Issue by pjsalisbury** [xpublish-community/xpublish-wms#50]
On some NetCDF datasets, making a GetMap request throws a TypeError during the projection: `TypeError: unhashable type: 'slice'`

The error seems to occur on line 360 in grid.py (inside mask() for ROMSGrid): `mask[:-1, :] = mask[:-1, :].where(mask[1:, :] == 1, 0)`. Putting some breakpoints in the code showed that on our NetCDF dataset that does work, this code section is not used (because the working dataset uses HYCOMGrid instead of ROMSGrid). 

Here is an example of a dataset that produces the error: https://noaa-ofs-pds.s3.amazonaws.com/cbofs.20231128/nos.cbofs.fields.f004.20231128.t12z.nc

**Comment by mpiannucci** [comment]
Okay give the latest main branch a test, think it should be all set now

**Comment by pjsalisbury** [comment]
Looks like it does work, but there is an odd behavior right now (with only the datasets that didn't load before this fix) where you lose data around the edges with repeated calls to the same (cached?) dataset. I attached a couple videos showing the issue on both tbofs and cbofs datasets

https://github.com/xpublish-community/xpublish-wms/assets/93105418/d920c519-d5a7-41af-8db9-786eaa7bc3fb


https://github.com/xpublish-community/xpublish-wms/assets/93105418/5c89ec10-e694-448b-952e-f510027bd86d

**Comment by mpiannucci** [comment]
Interesting. Does it always work on first hit cold? I am going to guess this is a general server issue rather than a specific grid issue

**Comment by pjsalisbury** [comment]
It always works on the first hit cold, but starts losing data on the second hit and continues until I restart the server. GRIB and NetCDF datasets that worked for me previously (rtofs) don't show the issue at all even after a ton of refreshes which is why I thought it might be related to the specific grid. 

Let me know if there's something specific I should try, or if it doesn't seem like too big of an issue I will ignore it for now and move on.

**Comment by pjsalisbury** [comment]
Latest commit successfully resolved this for me

**Comment by mpiannucci** [comment]
Awesome! Yeah weird masking issue going on with non time dimensioned datasets. Glad it fixed for you too!
