### ISSUE TITLE
Release

### ISSUE THREAD

**Issue by abkfenris** [xpublish-community/xpublish-wms#9]
@mpiannucci Now that Xpublish 0.3.0 is released with plugin support, do you want me to get PyPI and Conda-Forge releases going for this package? I've got them working for OpenDAP and EDR plugins.

**Comment by mpiannucci** [comment]
Yea that would be great. I am close to being ready to release a more generally applicable api.

**Comment by abkfenris** [comment]
Ok, the repo should be prepped for releases. @mpiannucci while you could tag and create a Github Release now, it may be worth waiting for Conda-Forge to get caught up. 

Currently the repo is getting initialized which may take an hour-ish https://github.com/conda-forge/xpublish-wms-feedstock

Once that's ready (we'll get tagged in a comment on an automatically generated commit), then creating a 0.1.0 release here will make a release on PyPI, and within 24 hours Conda-Forge should pick it up.

**Comment by mpiannucci** [comment]
Sounds good. I have a new branch I need to merge in this week, so i will tag the release once the more robust branch is merged in. 

Thanks for everything @abkfenris

**Comment by abkfenris** [comment]
And there the comment is https://github.com/conda-forge/xpublish-wms-feedstock/commit/52c7f1ce33da07a4f6071fd6d8deda449538ecea#commitcomment-113436771

The build is in progress, give it a few hours and it should be installable from conda-forge. https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=705710&view=results
